config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'products#index'

  resources :categories, :products, only: [:index, :show]
  resources :orders

  resource :cart, only: [:show]
  resources :carts do
    member do
      post :add_product_to
      patch :remove_product_from
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

  scope :clear, -> (cart_id) { find(cart_id).cart_products.destroy_all }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    if user_signed_in?
      @cart = resource
    else
      @products = @cart.present? ? @cart.products : Product.where(id: session[:product_ids])
    end
  end

  def add_product_to
    if user_signed_in?
      current_user.cart.products << Product.find(params[:id])
    elsif session[:product_ids].present?
      session[:product_ids] << params[:id]
    else
      initialize_session_cart
    end
     redirect_to cart_path
  end

  def remove_product_from
    if user_signed_in?
      current_user.cart.products.destroy(params[:id])
    else
      session[:product_ids].delete(params[:id])
    end
     redirect_to cart_path
  end

  private

  def resource
    current_user.cart
  end

  def initialize_session_cart
    session[:product_ids] = []
    session[:product_ids] << params[:id]
  end
end

app/views/carts/_cart_product.html.erb
<div class="flex flex-row justify-around">
<p class = "cart-item"><%= product.name %></p>
<p class = "cart-item"><%= product.category.name %></p>
<p class = "cart-item"><%= product.price %></p>
<%= button_to 'Delete', remove_product_from_cart_path(product), method: :patch, class:'w-20 btn-pink my-8' %>
<%= link_to 'Show', product_path(product), class:'w-20 btn-pink my-8' %>
</div>

app/views/carts/show.html.erb
<% if user_signed_in? %>
  <% if @cart.products.present? %>
    <div class="cart-container">
      <% @cart.products.each do |product| %>
        <%= render 'carts/cart_product', product: product %>
      <% end %>
      <%= link_to 'Make order', new_order_path, class: "btn-blue w-40 mx-auto my-6" %>
    </div>
  <% else %>
    <div class="empty-cart-container w-2/4">
      <%= "Your cart is empty. Let`s discover our assortiment!" %>
      <%= link_to 'Show products', root_path, class: "h-12 btn-blue" %>
    </div>
  <% end %>
<% else %>
  <% if @products.present? %>
    <div class="cart-container">
      <% @products.each do |product| %>
        <%= render 'carts/cart_product', product: product %>
      <% end %>
      <%= link_to 'Make order', new_order_path, class: "btn-blue mx-auto my-6" %>
    </div>
  <% else %>
    <div class="empty-cart-container w-2/4">
      <%= "Your cart is empty. Let`s discover our assortiment!" %>
      <%= link_to 'Show products', root_path, class: "btn-blue w-40 mx-auto mt-6" %>
    </div>
  <% end %>
<% end %>