config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'products#index'

  resources :categories, :products, only: [:index, :show]
  resources :orders

  resource :cart, only: [:show]
  resources :carts do
    member do
      post :add_product_to
      patch :remove_product_from
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  scope :ordered, -> { order(position: :desc) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = collection
  end

  def show
    @category = resource
  end

  private

  def collection
    Category.ordered
  end

  def resource
    collection.find(params[:id])
  end
end

app/views/categories/index.html.erb
<div class="max-w-5xl mx-auto">
  <% @categories.each do |category| %>
    <div class="product-card">
      <p class="py-2.5 text-xl font-bold w-4/5 m-auto"><%= category.name %></p>
      <%= link_to "SHOW PRODUCTS", category_path(category), class: "w-28 btn-pink mx-auto" %>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="max-w-5xl mx-auto">
  <% @category.products.each do |product| %>
    <div class="product-card">
      <p class="card-text"><%= product.name %> </p>
      <p class="card-text"><%= product.description %></p>
      <p class="card-text"><%= product.price %><p>
      <%= button_to "Buy", add_product_to_cart_path(product), class: "w-28 btn-pink" %>
    </div>
  <% end %>
</div>