config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'products#index'

  resources :categories, :products, only: [:index, :show]
  resources :orders

  resource :cart, only: [:show]
  resources :carts do
    member do
      post :add_product_to
      patch :remove_product_from
    end
  end
end

app/views/layouts/_navbar.html.erb
<div class="bg-pink-500">
<nav class="max-w-7xl m-auto bg-pink-500 shadow md:flex md:items-center md:justify-between">
    <div class="flex items-center justify-between">
      <%= link_to (image_tag 'logo.png'), root_path, method: :get, class: "w-32 cursor-pointer" %>
      <span class="block mx-2 text-3xl cursor-pointer md:hidden">
        <ion-icon name="menu" onclick="Menu(this)"></ion-icon>
      </span>
    </div>

    <ul class=" md:flex md:items-center md:z-auto md:static absolute bg-pink-500 w-full left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-7 md:opacity-100 opacity-0 top-[-400px] transition-all ease-in duration-500">
      <li class="mx-4 mr-20 md:my-0">
        <%= link_to "ALL PRODUCTS", root_path, class: "text-xl text-white duration-500 hover:text-cyan-500 font-semibold" %>
      </li>
      <li class="mx-4 mr-20 md:my-0">
        <%= link_to "CATEGORIES", categories_path, class: "text-xl text-white duration-500 hover:text-cyan-500 font-semibold" %>
      </li>
      <% if user_signed_in? %>
          <%= link_to (image_tag 'cart.png'), get_cart_path, method: :get, class: "hover:bg-purple-800 mr-16 mb-2" %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-6 mb-2" %>
          <div class = "text-white text-based font-medium">
            <%= current_user.email %>
          </div>
          <% else %>         
            <%= link_to new_user_session_path do %>
              <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Log in</button>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <button type="button" class="text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Sign up</button>
            <% end %>
            <%= link_to (image_tag 'cart.png'), get_cart_path, method: :get, class: "hover:bg-purple-800 mr-2 mb-2" %>
          <% end %>

    </ul>
    
          
  </nav>
  <script>
    function Menu(e){
      let list = document.querySelector('ul');
      e.name === 'menu' ? (e.name = "close",list.classList.add('top-[80px]') , list.classList.add('opacity-100')) :( e.name = "menu" ,list.classList.remove('top-[80px]'),list.classList.remove('opacity-100'))
    }
  </script>
</div>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script  src="./js/script.js"></script>
    <script src="https://kit.fontawesome.com/bdb0b9b1d1.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render 'shared_links/navbar' %>
    <main>
      <%= yield %>
    </main>
  </body>

</html>